[symbolic] Add CI support for basic symbolic tracing
panda-re/panda pull request #1064
Opened 2021-08-04 01:44 UTC by buszk

Previous PR #1061 introduced a regression that causes Segfault.
This PR should have it fixed and adds a basic CI test for symbolic tracing.

Add comments for the symbolic tracing functions to make them more readable

2021-08-06 01:57 UTC, buszk commented
Address #1048 
Download and install libz3 4.8.7 to `/usr/local/` on Ubuntu 18

2021-08-09 15:10 UTC, AndrewFasano requested changes

2021-08-09 15:10 UTC, AndrewFasano commented on panda/python/core/pandare/panda.py
> +from ctypes import sizeof
Is there a way to do this with CFFI instead of adding the dependency on ctypes?

2021-08-09 15:10 UTC, AndrewFasano commented on panda/python/core/pandare/panda.py
> +            hex(meta_ffi.pc)
Should this return as an int instead of a string? I.e., it could just be `meta_ffi.pc` here?

2021-08-11 20:58 UTC, AndrewFasano approved these changes

2021-08-11 20:58 UTC, AndrewFasano commented
Thanks for making those changes!

2021-08-11 20:58 UTC, merged