Add userdata context variable API to PPP callbacks
panda-re/panda pull request #1116
Opened 2021-10-22 21:04 UTC by jamcleod

See #1105 for additional context as to the rationale. As for the implementation--PPP callbacks were trickier and required a minor breaking change. The typedefs for PPP callbacks must now be generated using the `PPP_CB_TYPEDEF` macro. Unlike the base callback implementation, this implementation doesn't use trampoline generation and simply hold a separate callback list for those with context variables.

2021-10-22 21:07 UTC, jamcleod commented
Worth noting for anyone who reviews: only these first 3 files are particularly relevant. Most of the rest of the 15k line diff is just migrating the breaking change

![image](https://user-images.githubusercontent.com/69213264/138523016-eaff2484-073b-4a2a-abea-7d98b0108f48.png)

2021-10-22 21:08 UTC, AndrewFasano commented on panda/plugins/syscalls2/scripts/syscall_parser.py
> +        return '{0} arg{1} = 0;'.format(self.ctype, self.no)
Can all these types be assigned to an actual 0 or do you want to initialize to an empty value with `{0}`?

2021-10-22 21:09 UTC, AndrewFasano requested changes
Code changes look good to me (assuming CI passes) - but you should update the docs for PPP functions too so new plugins will be created with the right macros

2021-10-25 17:29 UTC, AndrewFasano commented
Pretty sure the CI failure is just a one-off-bug in the CI, not an issue with this PR. Merging 🙈

2021-10-25 17:30 UTC, AndrewFasano approved these changes

2021-10-25 17:30 UTC, merged