Use libosi to handle windows introspection
panda-re/panda pull request #1138
Opened 2021-12-02 16:56 UTC by Ben-Dumas

Use [panda-re/libosi](https://github.com/panda-re/libosi) library to handle windows introspection 

1. removes the existing `win*` plugins, and IMO simplifies the wintrospection plugin. 
2. splits out the windows-32-7 profile into windows-32-7sp[01]. 
3. slightly improves handle name stringifying (now registry keys are parsed) 
4. adds 64-bit support for windows7

this has been verified on ubuntu 20.04 for 32/64-bit Windows 7, 32-bit Windows XP, and 32-bit Windows 2000. I tested `osi_test`, `file_taint`, and `syscalls2` with the new library. happy to test anywhere else if i missed something!

2021-12-02 20:54 UTC, jamcleod commented
@Ben-Dumas it seems like your usage of `$_` is causing issues while building the docker container:

```
#12 [builder 4/7] RUN cd /tmp &&   git clone https://github.com/panda-re/libosi &&   mkdir libosi/build && cd $_ &&   cmake -GNinja .. && ninja && ninja package && dpkg -i libosi*.deb &&   cd /tmp && rm -rf libosi/
#12 sha256:8422d06c53f2ec6cf74152e23dfa6176552bf7f325dfe8d3bd95f57198ee1c2b
#12 0.338 Cloning into 'libosi'...
#12 0.769 CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
```
(See the `build_container` test)

2021-12-17 01:23 UTC, lacraig2 commented on panda/plugins/wintrospection/pandamemory.cpp
> +    buffer[ix] = papm->get_byte(current_addr);
This seems like a really inefficient way to read virtual memory. You'll end up doing a virtual memory address translation every time you look up a byte.

2021-12-17 01:25 UTC, lacraig2 commented on panda/plugins/wintrospection/pandamemory.cpp
> +      panda_physical_memory_rw(addr, &retval, 1, 0);
Consider using `panda_virtual_memory_read` instead. It's just an inline that places the 0 for `is_write`.

2021-12-17 01:28 UTC, lacraig2 commented on panda/plugins/wintrospection/pandamemory.cpp
> +      panda_physical_memory_rw(addr, &retval, 1, 0);
This. To my suprise. Does not exist. I'll write up a quick PR to make it to parity with `panda_virtual_memory_*`.

2021-12-17 01:32 UTC, lacraig2 requested changes
Just some small things to consider.

2021-12-17 01:32 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> + *  Brendan Dolan-Gavitt   brendandg@gatech.edu
I feel like @Ben-Dumas your name should really be up here as well.

2021-12-17 01:32 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +  pcb.before_block_exec = before_block_exec;
Consider using `start_block_exec` over `before_block_exec`. This will allow the plugin to run without chaining disabled.

2021-12-17 01:32 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +  // if we don't clear tb's when this exits we have TBs which can call
Do you have hooks somewhere that I'm not seeing? Are you doing TCG injection somewhere?

2021-12-17 01:46 UTC, lacraig2 commented on panda/plugins/wintrospection/pandamemory.cpp
> +      panda_physical_memory_rw(addr, &retval, 1, 0);
This will be available when PR #1148 closes.

2021-12-17 02:03 UTC, Ben-Dumas commented on panda/plugins/wintrospection/wintrospection.cpp
> +  // if we don't clear tb's when this exits we have TBs which can call
ah, this was left over from when i started with `wintrospection.c` plugin

https://github.com/panda-re/panda/blob/dev/panda/plugins/wintrospection/wintrospection.c#L870-L875

Will remove

2021-12-17 02:30 UTC, Ben-Dumas commented on panda/plugins/wintrospection/wintrospection.cpp
> +  pcb.before_block_exec = before_block_exec;
Interesting, I didn't know that. 
Should i call `panda_enable_tb_chaining`, or are you just referring to allowing a live system (vs replay) to run?

2021-12-17 02:39 UTC, Ben-Dumas commented on panda/plugins/wintrospection/pandamemory.cpp
> +    buffer[ix] = papm->get_byte(current_addr);
This was taken from the way we've handled memory snapshots in the past [here](https://github.com/panda-re/libosi/blob/master/src/iohal/memory/pmem_snapshot.cc#L55-L69). But that's fair! I'll check it out and see if If changing it improves performance (or if i can figure out why we did it that way in the first place).

2021-12-17 02:58 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +  // if we don't clear tb's when this exits we have TBs which can call
Gotcha. Turns out that _was_ necessary when the old plugin was doing TCG insertion for hooking the task change address.

2021-12-17 02:58 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +  // if we don't clear tb's when this exits we have TBs which can call
See: https://github.com/panda-re/panda/blob/dev/panda/plugins/wintrospection/wintrospection.c#L740

2021-12-17 02:59 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +bool asid_changed(CPUState *cpu, target_ulong old_pgd, target_ulong new_pgd) {
Is it possible to manage tasks changing like the current wintrospection plugin does with hooks on the task change function? https://github.com/panda-re/panda/blob/d4c6508d0b0e39bec20b32429cbdfa9836ded2fe/panda/plugins/wintrospection/wintrospection.c#L740

If so you could likely replace this logic with a hook.

2021-12-17 03:01 UTC, lacraig2 commented on panda/plugins/wintrospection/pandamemory.cpp
> +    buffer[ix] = papm->get_byte(current_addr);
I can see it being reasonable in that example. It might be fine, but the overhead of repeatedly doing this logic (https://github.com/panda-re/panda/blob/fcd26ede117337fe68610391d4451a508f41201f/panda/include/panda/common.h#L76-L95) x the number of bytes seems like it might be an issue.

2021-12-17 04:33 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +  pcb.before_block_exec = before_block_exec;
If you don't enable `tb_chaining` the callback `before_block_exec` is not guaranteed to run on every block. That is to say that if PANDA runs a chain of TBs you wont see the intermediary blocks.

It's not always required to disable `tb_chaining` for every `bbe`, but if you want that guarantee you must disable it.

That was the case util we added `start_block_exec`. `start_block_exec` is TCG instrumentation in every block that calls our callback. That way even if PANDA runs a chain of TBs we maintain the guarantee to run on every block.

2021-12-17 15:55 UTC, Ben-Dumas commented on panda/plugins/wintrospection/wintrospection.cpp
> + *  Brendan Dolan-Gavitt   brendandg@gatech.edu
changed names to myself and other two that have worked with wintrospection/libosi in the past! I've always just used the panda standard comment 🤷

2021-12-17 17:08 UTC, lacraig2 commented on panda/plugins/wintrospection/pandamemory.cpp
> +      panda_physical_memory_rw(addr, &retval, 1, 0);
PR #1148 merged so feel free to add.

2021-12-17 19:40 UTC, Ben-Dumas commented on panda/plugins/wintrospection/wintrospection.cpp
> +bool asid_changed(CPUState *cpu, target_ulong old_pgd, target_ulong new_pgd) {
Is that more accurate than waiting for the ASID to change? I could change it back; I just liked that this method isn't OS-version dependent.

2021-12-17 21:02 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +bool asid_changed(CPUState *cpu, target_ulong old_pgd, target_ulong new_pgd) {
We found that for `osi_linux` hooking on the task change function was not only more performant, but far more accurate.

I can really only speak to the linux side of it, but I do believe there will be windows equivalents. There's quite a few cases where the ASID doesn't accurately reflect the process. One example is `fork`. When the OS creates a new process it doesn't necessarily have to create new page tables for the process through Copy On Write (COW). Another example is `execve`, which may well reuse the same page table address when it "replaces" the process. This might result in the ASID not changing, but the underlying process changing.

2021-12-17 21:03 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +bool asid_changed(CPUState *cpu, target_ulong old_pgd, target_ulong new_pgd) {
If you're looking for something more OS-agnostic you could consider adding logic to the libosi library to handle this and calling it?

2022-01-04 19:14 UTC, Ben-Dumas commented on panda/plugins/wintrospection/wintrospection.cpp
> +bool asid_changed(CPUState *cpu, target_ulong old_pgd, target_ulong new_pgd) {
what about this newest commit (https://github.com/panda-re/panda/pull/1138/commits/a88a22bebc4570351eaa12e4732560dca74746f1)? Here, I use the address of `nt!SwapContext` *if it is known* by libosi. Otherwise, it falls back to the startblock/asid_change method. This way, a user can always improve their accuracy by determining the address for their OS version, but they have something to fall back on. The offsets are currently set for the profiles that were previously supported.

2022-01-04 20:51 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +bool asid_changed(CPUState *cpu, target_ulong old_pgd, target_ulong new_pgd) {
Looks good. I changed it around to use `hooks`, but other than that it looks great.

2022-01-04 20:54 UTC, lacraig2 approved these changes

2022-01-04 20:54 UTC, lacraig2 commented on panda/plugins/wintrospection/wintrospection.cpp
> +#include <offset/i_t.h>
Some method of keeping versions of wintrospection and libosi in sync would be good.

2022-01-05 19:11 UTC, merged

2022-01-05 19:17 UTC, AndrewFasano commented
🥳 Nice work @Ben-Dumas, thanks for upstreaming your code!!

(And thanks as always to @lacraig2 for getting it tested and merged)

2022-01-11 15:00 UTC, Coffeeri commented
This looks great, thank you! I am currently trying to use Panda and get the PEB content, Windows API calls of a process.
Is there any documentation on the new API and how to use the new wintrospection plugin and library?

2022-01-11 16:19 UTC, Ben-Dumas commented
@Coffeeri I'm glad you might find it useful! feel free to submit issues/PRs to [libosi](https://github.com/panda-re/libosi) for issues you're having! But in general -

The `wintrospection` plugin should give you an example of initializing windows introspection. To walk through it, once the kernel introspection [is initialized](https://github.com/panda-re/panda/blob/dev/panda/plugins/wintrospection/wintrospection.cpp#L621-L637), you can interact with memory using the [`osi::i_t` class](https://github.com/panda-re/libosi/blob/master/include/offset/i_t.h) or the [windows introspection API](https://github.com/panda-re/libosi/blob/master/include/osi/windows/wintrospection.h). You would probably want to [initialize introspection](https://github.com/panda-re/panda/blob/dev/panda/plugins/wintrospection/wintrospection.cpp#L516-L518) for the currently running process and then access the PEB [like this](https://github.com/panda-re/panda/blob/dev/panda/plugins/wintrospection/wintrospection.cpp#L231-L242). After that, we don't currently have a good way of knowing what types are available for you to use, outside of just looking at the code ☹️ For example, looking at windows-64-7sp1, I know i have [these types](https://github.com/panda-re/libosi/blob/master/src/offset/profiles/win7_sp1_x64.cpp#L4315-L4406) for the PEB.  

You can currently get a list of all processes, get a list of all modules, resolve handles to get a pointer to the object, and parse PE files in memory. The libosi library is still in a very early state, and documentation *should* definitely get added into the pipeline; that's a good point.

To your question of how to use `wintrospection`, it's not too different from other plugins (just make sure to give the `os` flag):

```bash
$PANDA_PATH/x86_64-softmmu/panda-system-x86_64 -replay mytrace \
  -m 2G -os windows-64-7sp1 -panda osi -panda wintrospection -panda osi_test
```

If you have any more questions, follow up with me via email (Benjamin.Dumas@ll.mit.edu) now that this PR is closed.