fixing up mips r28 sync
panda-re/panda pull request #1156
Opened 2022-01-05 18:12 UTC by lacraig2

- changes first_osi_check switch to syscall method to wait until r28 has been read at least once
- changes MIPS bbe to sbe
- adds new `address_in_kernel_code_linux` from functionality in `panda_in_kernel_code_linux`
- reorganizes r28 cache code to use new call (address now supports MIPS64)

CLOSES: #990

2022-01-05 19:54 UTC, AndrewFasano commented
Any chance you could just pull in #1142 with this? They seem to overlap a bit

2022-01-05 19:55 UTC, AndrewFasano commented
Sorry, I haven't had time to address the changes requested there, but it seems like you've made some of them here

2022-01-05 23:16 UTC, lacraig2 commented
Sure. I've pulled in that one too.

2022-01-06 00:01 UTC, AndrewFasano commented
Other than the CI failures, this looks great to me. Thanks so much for pulling in the code from that other PR. I swear I was going to address your feedback soon, but I'm having a bit of a busy month right now.

2022-01-06 16:25 UTC, off-by-1-error requested changes
small typo in `hw_proc_id_int_fns.h` 

everything else looks good!

2022-01-06 16:25 UTC, off-by-1-error commented on panda/plugins/hw_proc_id/hw_proc_id_int_fns.h
> +bool is_is_initialized(void);
id_is_initialized?

2022-01-06 16:54 UTC, lacraig2 commented on panda/plugins/hw_proc_id/hw_proc_id_int_fns.h
> +bool is_is_initialized(void);
Good catch. Thanks.

2022-01-12 16:25 UTC, merged

2023-07-25 19:47 UTC, MarkMankins commented on panda/plugins/osi_linux/osi_linux.cpp
> +                ret = NULL;
Should this (and line 336 below) be:  *ret = NULL;    ?