move avatar output (i.e., configurable machine) behind log flag
panda-re/panda pull request #1175
Opened 2022-02-18 21:23 UTC by mariusmue

In case you ever used avatar's configurable machine and where annoyed by all the logging output of created memory regions and similar, this PR provides the solution!
These prints are now guarded by qemu's logging/log_mask infrastructure. This required to adjust the type of the qemu log mask from int to long - but this change should be backwards compatible either way.

2022-02-19 00:56 UTC, lacraig2 requested changes
Everything else looks good. Not changing to a `long` would simplify this significantly.

2022-02-19 00:56 UTC, lacraig2 commented on include/qemu/log.h
> +extern long qemu_loglevel;
Do we need to change this to a long? There's definitely still room in the `int` for an AVATAR log.

P.S. PR #1114 will add a `LOG_PANDA` so it'd be good to not use 17. 18-27 are available though!

2022-02-19 01:03 UTC, lacraig2 commented
I merged that other old PR and fixed the conflict with this PR.

2022-02-20 18:11 UTC, mariusmue commented on include/qemu/log.h
> +extern long qemu_loglevel;
Good catch for 18-27, I didn't realize and just appended after the last #define! Updated that branch accordingly

2022-02-21 10:08 UTC, mariusmue commented
Uhm. I think the current CI failures are not related to my log_mask changes - how would we move forward here?

2022-02-23 20:43 UTC, lacraig2 commented
You're right. I'll run it again.

2022-02-23 20:47 UTC, lacraig2 commented
I went ahead and added this log mechanism to `qemu_logging.py` in pypanda. That'll let you selectively turn on/off various log types dynamically.

2022-02-23 20:51 UTC, lacraig2 approved these changes

2022-02-25 16:21 UTC, merged