Fix taint inconsistency
panda-re/panda pull request #1185
Opened 2022-03-08 21:02 UTC by lacraig2

This PR resolves a taint inconsistency present in the wrapper for pypanda. This should resolve #711.

Essentially, two problems existed:
- using `queue_main_loop` can significantly delay actions past the point at which a taint should have been applied
- The system allowed taint to be enabled in the same context as it was used. This can not be done. Taint must be enabled at least 1 block prior to being used.

2022-03-09 15:30 UTC, AndrewFasano requested changes
It's great to see this issue finally being addressed! Just have a few small nits and one actual bug.

2022-03-09 15:30 UTC, AndrewFasano commented on panda/python/core/pandare/panda.py
> +            self.plugins["taint2"].taint2_label_reg(reg_num, i, label)
Now that the taint plugin will definitely be loaded prior to this is it okay to apply labels immediately here and on 1907 instead of waiting until the next main loop?

2022-03-09 15:30 UTC, AndrewFasano commented on panda/python/core/pandare/panda.py
> +        self._assert_taint_enabled()
Thoughts on just returning False if taint isn't enabled? Both here and in taint_check_ram? I think that was the old behavior - but I'm not opposed to changing it.

2022-03-09 15:30 UTC, AndrewFasano commented on panda/python/core/pandare/panda.py
>          self.taint_sym_enable(cont=False)
This needs to be updated - cont is no longer an option to taint_sym_enable

2022-03-10 00:57 UTC, lacraig2 commented on panda/python/core/pandare/panda.py
>          self.taint_sym_enable(cont=False)
Good catch. Fixed. Thanks.

2022-03-10 00:59 UTC, lacraig2 commented on panda/python/core/pandare/panda.py
> +        self._assert_taint_enabled()
I don't think that returning False is appropriate here. I think if you ask for taint information without it being enabled that's an error of which you should generally be aware. In C, this would result in either a segfault or an assertion thrown.

2022-03-10 01:00 UTC, lacraig2 commented on panda/python/core/pandare/panda.py
> +            self.plugins["taint2"].taint2_label_reg(reg_num, i, label)
Yes. I believe so. As long as the assertions are met I believe we should be able to handle this behavior. The key difference here is that these are done deterministically.

2022-03-10 02:17 UTC, merged