callbacks: normalize plugin name path
panda-re/panda pull request #1189
Opened 2022-03-16 22:55 UTC by lacraig2

This PR normalizes the panda path to plugins such that the realpath is provided back. This resolves an issue whereby plugins could be loaded from different sources with different visible paths that resolve to the same path. Because our comparison for the plugin loaded is done by the abolute path this can lead to a situation where the same plugin is loaded multiple times.

2022-03-23 19:24 UTC, jamcleod commented on panda/src/callbacks.c
> +static char* attempt_normalize_path(char* path){
The lifetime of the path returned by `attempt_normalize_path` is ambiguous.

Either:
1. normalization succeeds and the caller is responsible for freeing the path, so the caller should free the output and (if already responsible for it) the input.
2. normalization fails and the caller should not separately free both the returned path and the input

So the options are either:
1. have the caller responsible for handling failures of `realpath`
2. memcpy path to new_path on error and return new_path unconditionally
3. use an out parameter to indicate whether the lifetime of the return value is owned or borrows from the input (if you're familiar--this is basically `Cow<'a, str>` in Rust)
4. leak memory if `realpath` succeeds (eg never free the return value of `attempt_normalize_path`)

Currently I believe you're choosing option 4.

2022-03-23 19:26 UTC, jamcleod commented on panda/src/callbacks.c
> +    const char* rfilename = attempt_normalize_path((char*)filename);
`rfilename` should not be const as it is responsible for freeing its contents

2022-03-23 19:32 UTC, jamcleod commented on panda/src/callbacks.c
> +        char *pn = g_path_get_basename((char *) rfilename);
this cast is casting away a const (unnecessarily, even, `g_path_get_basename` takes a `const gchar*`, which is a type alias for `const char*`)

2022-03-23 19:36 UTC, jamcleod requested changes
Minor issues regarding path lifetimes and const-correctness, once those are fixed, looks good to me.

2022-03-23 19:36 UTC, jamcleod commented on panda/src/callbacks.c
> +    plugin_path = attempt_normalize_path(
this duplicates the path twice without freeing either copy

2022-03-24 02:58 UTC, lacraig2 commented on panda/src/callbacks.c
> +        char *pn = g_path_get_basename((char *) rfilename);
yes. removed cast.

2022-03-24 02:58 UTC, lacraig2 commented on panda/src/callbacks.c
> +static char* attempt_normalize_path(char* path){
Fair. #2 sounds like a reasonable option.

2022-03-24 03:00 UTC, lacraig2 commented on panda/src/callbacks.c
> +    plugin_path = attempt_normalize_path(
should be resolved with the changes to `attempt_normalize_path`

2022-03-24 03:01 UTC, lacraig2 commented on panda/src/callbacks.c
> +    const char* rfilename = attempt_normalize_path((char*)filename);
yes.

2022-03-24 15:23 UTC, jamcleod approved these changes
One more minor issue about const correctness, but looks good to me.

2022-03-24 15:23 UTC, jamcleod commented on panda/src/callbacks.c
> +    g_free((char*)path);
If `path` is assumed to be owned (and thus `attempt_normalize_path` is responsible for freeing it) then `path` shouldn't be a `const` pointer. I'd say just change `path` to a `char*` and add a comment above the function stating that `attempt_normalize_path` takes ownership of the input path. 

And while imo not worth the effort, if you really want to take it even further it'd reduce allocator churn in the error case to return `new_path` on success and `path` on error (which, unlike before, is fine assuming that `attempt_normalize_path` takes ownership of its input). I wouldn't bother though.

2022-03-24 18:24 UTC, lacraig2 commented on panda/src/callbacks.c
> +    g_free((char*)path);
Seems reasonable. Yes that should be `char*` and not `const char*`.

2022-08-24 15:15 UTC, AndrewFasano commented
Closing and reopening this to get CI to run

2022-09-01 21:26 UTC, merged