RR2 file compressed format
panda-re/panda pull request #1194
Opened 2022-04-14 17:48 UTC by zacogen

Add code for using rr2 file compressed format in record and replay.
More details on format in https://github.com/panda-re/panda/issues/1087

2022-04-27 18:17 UTC, lacraig2 reviewed
Seems like a good start. I'd like some more clarification on the plan for old recordings.

2022-04-27 18:17 UTC, lacraig2 commented on panda/src/rr/rr_log.c
> +	    break;
formatting looks a bit broken.

2022-04-27 18:17 UTC, lacraig2 commented on configure
> +##########################################
Dependencies added here need to be added to Docker config files.

2022-04-27 18:17 UTC, lacraig2 commented on scripts/rr_pack.py
> +import os
This script should be moved to /panda/scripts. /scripts if for QEMU scripts.

2022-04-27 18:17 UTC, lacraig2 commented on panda/include/panda/rr/rr_log.h
> +    union {
The union here makes me think that this supports both the old system and the new. Is that the case?

2022-05-17 22:09 UTC, zacogen commented on panda/include/panda/rr/rr_log.h
> +    union {
Originally, I had the code only supporting the new rr2 format, however this commit (https://github.com/panda-re/panda/pull/1194/commits/75a752a9520c3dbe1dfa8031f59bfb2d8949d38c) allows for the support of both rr2 and the older rr format for replay. 

Documentation on record and replay changes can be found here: https://github.com/panda-re/panda/pull/1194/files#diff-9b6b498aa794f6943da36f22f611f6fd99b868b5b98265db52ae1372b9170248

2022-07-11 17:28 UTC, lacraig2 requested changes, later dismissed
@zacogen It doesn't look like recordings requested from PyPANDA or the monitor actually create RR2 format recordings.

2022-07-11 17:28 UTC, lacraig2 commented on vl.c
> +    gargv = malloc(argc * sizeof(gargv));
why are we doing this?

2022-07-11 17:28 UTC, lacraig2 commented on panda/python/core/pandare/panda_expect.py
> -    def expect(self, expectation=None, timeout=30):
Why the change here?

2022-07-11 17:44 UTC, zacogen commented on panda/python/core/pandare/panda_expect.py
> -    def expect(self, expectation=None, timeout=30):
I found that the setting up the compressed file took slightly longer than the current method. I changed the default time to make sure the tests did not fail because of this.

2022-07-11 17:45 UTC, zacogen commented on vl.c
> +    gargv = malloc(argc * sizeof(gargv));
The `gargv` is used in `rr_log.c` to save the command line into the compressed folder. I malloced memory, so that the values in `gargv` aren’t overwritten. https://github.com/panda-re/panda/blob/98e2d2d55264fc170f63e880b9ea3d4f942f45f2/panda/src/rr/rr_log.c#L1533-L1545

2022-09-06 20:10 UTC, AndrewFasano commented on panda/docs/manual.md
> +    PANDA, which is named `<name>-rr.cmd`.
Since it says "two parts" before, should t his maybe say something more like "Also the command line used to run PANDA is stored in `<name>-rr.cmd`

2022-09-06 20:50 UTC, zacogen commented on panda/docs/manual.md
> +    PANDA, which is named `<name>-rr.cmd`.
Good catch, I need to change to "three parts". Though could also do separate sentence to emphasize two "core" parts, which are necessary for replay. Then another extra file, which can assist in setting up a replay correctly, by reminding you which arguments you used, and also can be used with retroactively creating an `rr2` file.

2022-11-05 06:47 UTC, merged