dynamic symbols and hooks updates
panda-re/panda pull request #867
Opened 2021-02-02 16:08 UTC by lacraig2

This PR totally redesigns the hooks plugin and adds a new plugin `dynamic_symbols`. 

## hooks

Hooks now have a different prototype and structure. They are now defined using the following structure:
```
typedef struct hook {
    target_ulong start_addr;
    target_ulong end_addr;
    target_ulong asid;
    panda_cb_type type;
    hooks_panda_cb cb;
    enum kernel_mode km;
    bool enabled;
} hook;
```

When setting a hook a user may select from a list of `block`-type callbacks (e.g. `BEFORE_BLOCK_EXEC`, `AFTER_BLOCK_EXEC`, etc). This will be the callback type they receive.

On receiving a hooked callback a user will receive, in addition to the normal callback arguments, a pointer to the hook that called the function. Users may, at this point, change the hook in any way they choose. If they choose to set `enabled` to false the hook will be removed from the pool.

This removes some functionality from hooks as well. We remove the ability to filter by `procname` and `libname` for a few reasons. 
  - Checking anything with OSI, even with caching, on every basic block is far too slow and the old model probably didn't work very well anyhow.
  - We have shifted to a callback scheme where callbacks triggered can be changed.

Filtering can still be achieved with ASID filtering. You must simply disable hooks whose ASIDs are associated with terminated processes to avoid hooks being triggered on recycled ASIDs.

```
@panda.hook(0xffffffff, enabled=True, kernel=False, cb_type="after_block_exec")

## dynamic_symbols

`dynamic_symbols` is a Linux-based PANDA plugin which automatically resolves the symbols for each ELF in memory for each process with the help of `osi`. Users can use `hook_symbol` to hook symbols which may be defined in the future.

For example:

```
@panda.hook_symbol("libc", "write")
def hook_write(env, tb, h):
    arg1 = panda.arch.get_arg(env,1)
    try:
        trout = panda.read_str(env, arg1)
    except:
        trout = "?"

    print(f"{panda.get_process_name(env)} write \"{trout}\" 0x{arg1:x}")
```

For a full example see: [here](https://github.com/panda-re/panda/blob/proc_lib_cov/panda/python/examples/bins.py)

2021-02-03 00:41 UTC, AndrewFasano requested changes
This looks fantastic. I'm really impressed by how complex this challenge is and the solutions you came up with. I was interested in this enough to actually read through all the code - so I left a bunch of comments, but they're all fairly minor and certainly don't need to be addressed unless you want to.

2021-02-03 00:41 UTC, AndrewFasano commented on panda/plugins/dynamic_symbols/dynamic_symbols_int_fns.h
> +#define MAX_PATH_LEN 256
Does this compiler directive break the pypanda cffi parser stuff? I assume it doesn't, but it directly violates the rules in the comment above it which is amusing

2021-02-03 00:41 UTC, AndrewFasano commented on panda/plugins/dynamic_symbols/tester.py
> +    qq = "[??]"
Shouldn't this try reading? Also, maybe only read/print up to `n` bytes?

2021-02-03 00:41 UTC, AndrewFasano commented on panda/plugins/hooks/USAGE.md
> +
So here disabled means deleted? No way to disable then later re-enable? If so the docs are clear, just double checking

2021-02-03 00:41 UTC, AndrewFasano commented on panda/plugins/hooks/hooks.cpp
> +    printf("handle_hook_return @ 0x%llx for \"%s\" in \"%s\" @ 0x%llx ASID: 0x%llx\n", (long long unsigned int)rr_get_guest_instr_count(), sh->name, sh->section, (long long unsigned int) s.address, (
Should this be guarded by like `if(debug)` or commented?

2021-02-03 00:41 UTC, AndrewFasano commented on panda/plugins/hooks/hooks.cpp
> +            printf("contains\n");
Comment/remove?

2021-02-03 00:41 UTC, AndrewFasano commented on panda/plugins/hooks/hooks.cpp
> +            }
I think this logic is duplicated a bunch? Could it be a macro? Like you could specify the `before_tcg_codegen_hooks` as a string and then parameterize the whole block using that as a variable?

2021-02-03 00:41 UTC, AndrewFasano commented on panda/plugins/hooks/hooks.cpp
> +            }
I guess the return types aren't all the same, but maybe it could be two versions (bool or void)? maybe not worth it

2021-02-03 00:41 UTC, AndrewFasano commented on panda/python/core/pandare/panda.py
> +            # Ultimately, our hook resolves as a beforde_block_exec_invalidate_opt callback so we must match its args
Is this still true? Also there's a typo `beforde`

2021-02-03 00:41 UTC, AndrewFasano commented
I guess I "requested changes" but if you want to ignore them all, that's fine by me.

2021-02-03 18:40 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +void gdb_helper(){};
Good catch. For some reason line number breakpoints weren't working for me so I created a blank function and set up a gdb function to break on `gdb_helper` and finish the function. So I could just add `gdb_helper()` wherever I wanted a breakpoint. I'll remove it.

2021-02-03 18:41 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +    printf("continuing onto the end\n");
Yes. It's debugging. I was checking to see if it ever got there. It hasn't yet, which is good, this is the failsafe if ever the first two methods don't work. I'll remove.

2021-02-03 18:45 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +        // 100 for sanity
It's an old comment from when I hadn't quite figured out the bounds and it was running off the end and I would set a maximum value. Removed.

2021-02-03 18:46 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +        }else{
Fair.

2021-02-03 18:49 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +    if (unlikely(!panda_in_kernel(env))){
`!panda_in_kernel` could not, itself, be characterized as likely or unlikely on a generic system.

You have to understand it in the context. We enable `bbe_execve` after an `sys_execve` type call. It then enters the kernel and waits for the very first userland call. When this function executed we expect hundreds of kernel blocks before a single userland block. That's why its unlikely that we're in userspace.

2021-02-03 18:49 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +                        panda_require("dynamic_symbols");
This should be `hooks`. Good catch. I copied that code over from the other plugin.

2021-02-03 18:52 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols_int_fns.h
> +#define MAX_PATH_LEN 256
It does not break things (though at one point it did break pycparser).

I don't think I wrote that autogenerated comment, but the "compiler directives" that are at issue are things like `ifdef` and `if` and such.

2021-02-03 18:54 UTC, lacraig2 commented on panda/plugins/hooks/hooks.cpp
> +            printf("contains\n");
yeah.

2021-02-03 18:56 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +        //char* dynamic_section = (char*)malloc(dynamic_phdr.p_filesz);
sure.

2021-02-03 18:57 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +string read_str(CPUState* cpu, target_ulong ptr){
I seem to write it a lot. It's probably worth doing, but I wouldn't want it to return an `std::string` and I also don't want to manage the memory. A prototype for something like this might be 

`void read_str(CPUState* cpu, target_ulong addr, char* buf, int maxlen)`

idk. probably worth doing at some point.

2021-02-03 19:02 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +    strncpy((char*) & blank.name, none, 5);
Yeah. I had thought I changed all these out. I can't make them pointers to NULL because they aren't managed memory. They're an inline part of the struct. I have changed this around to `memset` the strings to all `0`. I think that's a better solution.

2021-02-03 19:03 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +map<target_ulong, map<std::string, target_ulong>> mapping;
That's a good note. I'll remove those.

2021-02-03 19:09 UTC, lacraig2 commented on panda/plugins/hooks/USAGE.md
> +
I had previously returned a pointer to users on adding hooks. I removed that functionality so that you can only change hooks when they're actively run.

I suppose the question is, should users be able to maintain an active reference to hooks and, if so, what are the guarantees?

Without the ability to get references to hooks disabling hooks removes them because without a reference they can't be set back to enabled and therefore should be gone.

It's a difficult problem, especially when considering reasonable efficiency. We don't want to run every callback all the time. 

We could do something like give them unique identifiers (not pointers) back to the application and hold onto them and then disable the callback if all of them are disabled and then enable the callback type when something like `hook_enable_callback` is enabled? It's tough developing a model for it and this is a consequence of the one that I have taken. I'm certainly willing to take another look at that model if you have concerns.

2021-02-03 19:17 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +        if (panda_virtual_memory_read(cpu, dynamic_section + j*sizeof(ELF(Dyn)), (uint8_t*)&tag, sizeof(ELF(Dyn))) != MEMTX_OK){
That structure certainly exists a fair amount. However, there is still some variation (void) and also, it's an error case, so I'd rather keep it open so I can potentially put debug prints in there.

2021-02-03 19:18 UTC, lacraig2 commented on panda/python/core/pandare/panda.py
> +            # Ultimately, our hook resolves as a beforde_block_exec_invalidate_opt callback so we must match its args
It was before we talked about changing it. Now it is not. Removing.

2021-02-03 19:19 UTC, lacraig2 commented on panda/plugins/hooks/hooks.cpp
> +            }
It's just frustrating enough to not be quite that easy to macro. I mostly just don't want to. Perhaps at some point in the future.

2021-02-03 19:19 UTC, lacraig2 commented on panda/plugins/hooks/hooks.cpp
> +    printf("handle_hook_return @ 0x%llx for \"%s\" in \"%s\" @ 0x%llx ASID: 0x%llx\n", (long long unsigned int)rr_get_guest_instr_count(), sh->name, sh->section, (long long unsigned int) s.address, (
yeah. that should be debug.

2021-02-03 19:20 UTC, lacraig2 commented on panda/plugins/hooks/hooks.cpp
> +    printf("handle_hook_return @ 0x%llx for \"%s\" in \"%s\" @ 0x%llx ASID: 0x%llx\n", (long long unsigned int)rr_get_guest_instr_count(), sh->name, sh->section, (long long unsigned int) s.address, (
Though I expect it to be the first thing uncommented if something goes awry. But it's excessive in the larger cases, yes.

2021-02-03 19:21 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/tester.py
> +    qq = "[??]"
Yeah. Probably worth doing there. Changed.

2021-02-03 19:23 UTC, lacraig2 commented on panda/plugins/dynamic_symbols/README.md
> +You may alternatively get a callback when a specified symbol has been resolved.
I've changed this around to make it slightly more clear. Let me know what you think.

2021-02-03 19:27 UTC, lacraig2 commented
Definitely not! I appreciate the time and effort you put in to do a thorough review. I've commented on each of them and made changes where I felt necessary for this round. I resolved the easy ones.

2021-02-04 01:25 UTC, AndrewFasano commented on panda/plugins/hooks/USAGE.md
> +
Ah okay, this design makes sense! I was just thinking about #865 where I was annoyed that we couldn't disable and later re-enable but this makes sense. Efficiency is important for hooking.

2021-02-04 01:26 UTC, AndrewFasano commented on panda/plugins/dynamic_symbols/dynamic_symbols.cpp
> +string read_str(CPUState* cpu, target_ulong ptr){
Yeah, sounds like a problem for later

2021-02-04 01:26 UTC, AndrewFasano approved these changes

2021-02-04 19:41 UTC, merged